### ISSUE TITLE
-w parameter needs a number to work

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/senza#11]
~~~~
senza events application -w
Error: -w option requires an argument
~~~~

This works though:

~~~~
senza events application -w 1
~~~~

**Comment by hjacobs** [comment]
Yes, the option should not require an argument to make it more convenient

**Comment by tuxlife** [comment]
For now, it isn't possible with click...

https://github.com/mitsuhiko/click/issues/370

**Comment by drummerwolli** [comment]
from my experience after using senza for some weeks now and showing it to different colleagues, the old behaviour was mostly favored ... the behaviour now is considered a but, because it is contradicting with all the other options, which can be shortened and still have the same behaviour ... i think its not that hard to put a number behind "-w" ... please reconsider ...

**Comment by hjacobs** [comment]
@drummerwolli yes, I agree somehow --- also it was a breaking change which was not announced :-(
