### ISSUE TITLE
Add option --fail-on-traffic to delete command

### ISSUE THREAD

**Issue by rwitzel** [zalando-stups/senza#292]
A suggestion:

senza delete --fail-on-traffic mystack 123 should cause senza to check whether there is traffic directed to the stack. If there is traffic directed to the stack, the command fails.

We would always use this option (we delete stacks via Jenkins job) and would feel more comfortable with this option.

**Comment by hjacobs** [comment]
I think this is a reasonable feature request :smile:

**Comment by musiKk** [comment]
Shouldn't this be the default? I'd rather have a `--force`. The thing is, I don't think it's especially unreasonable to delete a stack with 2% traffic. Or 14%. What about 30% or 50%? What about 100%? At some point it becomes a "you rarely want to do that and if you do, you should really really want it". In order to keep it simple, the deletion should just be rejected by default if the stack receives any traffic at all.

**Comment by hjacobs** [comment]
@musiKk I slightly disagree here:

* I assume you have a CD pipeline (right?), so your process is automated and makes sure that it does the right thing
* when using Senza manually from the CLI, it's often about deleting test stacks or similar --- I don't want to  specify an additional option only to convince the tool to do the right think (the option quickly would become something like `rm -fr` where `-fr` is so common that it's always there, so the "safety" feature is gone)
* whether a stack receives traffic is not trivial to find out as the DNS record weights will not tell you whether actual traffic goes to the stack, i.e. removing traffic via DNS from a stack and immediately deleting the stack would still cause havoc due to DNS caching (TTL) and client connection pools 
* there are also other reasons why a stack might not be safe to delete, just think about long running computation processes or jobs or other "stateful" stacks or configuration templates (e.g. creating a Senza template for security groups)

**Comment by musiKk** [comment]
* No. :(
* Speak for yourself. I'm prudent with `rm`'s force flag. Also, compare with `git clean` which explicitly requires `-f` or `-n` (or `-i`...) or `git branch`'s `-d`/`-D`. Of course, nobody hinders you to always `git branch -D` so you won't ever be presented with the option of failure from the tool but I certainly don't do it.
* Doesn't this prevent the implementation of this feature regardless of what flag is implemented?
* True, but that's not the point of this flag because the tool can't know (all) of those other reasons.

Now, the IMHO best option of all would also be inspired by git: Implement it however you want and give you the ability to configure a setting which enables/disables it by default.

**Comment by matosf** [comment]
I also think the default behavior should be to throw an error if it has traffic and you could force it using a flag (i.e. -f or --force), because when it comes to deleting things (i.e. actions that cannot be undone) we should never assume the user (being it manual or automated) will do the right thing, because... Murphy's law :).

The test stacks use case is not a valid argument IMO, because tooling should be made for the common use case (i.e. production), not edge cases.

**Comment by ainmosni** [comment]
I also think that the default should be to error when a stack still receives traffic. However, I think this should not be set as default right away. Maybe add a warning for a month or two so that people depending on the old behaviour won't be caught off guard.
