### ISSUE TITLE
senza traffic displays 0.0% weight for all stacks

### ISSUE THREAD

**Issue by woezelmann** [zalando-stups/senza#342]
When executing `senza traffic [name]` the results displays a weight of 0.0% for all stacks.
`senza domains` shows the weight correctly.

**Comment by GJL** [comment]
I have the same problem for some of my stacks.

**Comment by grzegorzjeziorski** [comment]
We drilled down a bit into code of senza to figure out source of this bug. It turns out that boto3.client.list_resource_record_sets used for fetching all dns records is setting implicitly MaxItems param to 100. So if you have too many records under one hosted zone some of them will never be taken into account. One can implement fetching all records using multiple invocations. 

http://boto3.readthedocs.io/en/latest/reference/services/route53.html#Route53.Client.list_resource_record_sets

**Comment by jmcs** [comment]
@grzegorzjeziorski thanks for troubleshooting this, I'll add pagination support.
